coreutils echo -e "@echo off \ncoreutils b2sum %%*" > b2sum.bat
coreutils echo -e "@echo off \ncoreutils b3sum %%*" > b3sum.bat
coreutils echo -e "@echo off \ncoreutils base32 %%*" > base32.bat
coreutils echo -e "@echo off \ncoreutils base64 %%*" > base64.bat
coreutils echo -e "@echo off \ncoreutils basename %%*" > basename.bat
coreutils echo -e "@echo off \ncoreutils basenc %%*" > basenc.bat
coreutils echo -e "@echo off \ncoreutils cat %%*" > cat.bat
coreutils echo -e "@echo off \ncoreutils cksum %%*" > cksum.bat
coreutils echo -e "@echo off \ncoreutils comm %%*" > comm.bat
coreutils echo -e "@echo off \ncoreutils cp %%*" > cp.bat
coreutils echo -e "@echo off \ncoreutils csplit %%*" > csplit.bat
coreutils echo -e "@echo off \ncoreutils cut %%*" > cut.bat
coreutils echo -e "@echo off \ncoreutils date %%*" > date.bat
coreutils echo -e "@echo off \ncoreutils dd %%*" > dd.bat
coreutils echo -e "@echo off \ncoreutils df %%*" > df.bat
coreutils echo -e "@echo off \ncoreutils dir %%*" > dir.bat
coreutils echo -e "@echo off \ncoreutils dircolors %%*" > dircolors.bat
coreutils echo -e "@echo off \ncoreutils dirname %%*" > dirname.bat
coreutils echo -e "@echo off \ncoreutils du %%*" > du.bat
coreutils echo -e "@echo off \ncoreutils echo %%*" > echo.bat
coreutils echo -e "@echo off \ncoreutils env %%*" > env.bat
coreutils echo -e "@echo off \ncoreutils expand %%*" > expand.bat
coreutils echo -e "@echo off \ncoreutils expr %%*" > expr.bat
coreutils echo -e "@echo off \ncoreutils factor %%*" > factor.bat
coreutils echo -e "@echo off \ncoreutils false %%*" > false.bat
coreutils echo -e "@echo off \ncoreutils fmt %%*" > fmt.bat
coreutils echo -e "@echo off \ncoreutils fold %%*" > fold.bat
coreutils echo -e "@echo off \ncoreutils hashsum %%*" > hashsum.bat
coreutils echo -e "@echo off \ncoreutils head %%*" > head.bat
coreutils echo -e "@echo off \ncoreutils join %%*" > join.bat
coreutils echo -e "@echo off \ncoreutils link %%*" > link.bat
coreutils echo -e "@echo off \ncoreutils ln %%*" > ln.bat
coreutils echo -e "@echo off \ncoreutils ls %%*" > ls.bat
coreutils echo -e "@echo off \ncoreutils md5sum %%*" > md5sum.bat
coreutils echo -e "@echo off \ncoreutils mkdir %%*" > mkdir.bat
coreutils echo -e "@echo off \ncoreutils mktemp %%*" > mktemp.bat
coreutils echo -e "@echo off \ncoreutils more %%*" > more.bat
coreutils echo -e "@echo off \ncoreutils mv %%*" > mv.bat
coreutils echo -e "@echo off \ncoreutils nl %%*" > nl.bat
coreutils echo -e "@echo off \ncoreutils numfmt %%*" > numfmt.bat
coreutils echo -e "@echo off \ncoreutils od %%*" > od.bat
coreutils echo -e "@echo off \ncoreutils paste %%*" > paste.bat
coreutils echo -e "@echo off \ncoreutils pr %%*" > pr.bat
coreutils echo -e "@echo off \ncoreutils printenv %%*" > printenv.bat
coreutils echo -e "@echo off \ncoreutils printf %%*" > printf.bat
coreutils echo -e "@echo off \ncoreutils ptx %%*" > ptx.bat
coreutils echo -e "@echo off \ncoreutils pwd %%*" > pwd.bat
coreutils echo -e "@echo off \ncoreutils readlink %%*" > readlink.bat
coreutils echo -e "@echo off \ncoreutils realpath %%*" > realpath.bat
coreutils echo -e "@echo off \ncoreutils rm %%*" > rm.bat
coreutils echo -e "@echo off \ncoreutils rmdir %%*" > rmdir.bat
coreutils echo -e "@echo off \ncoreutils seq %%*" > seq.bat
coreutils echo -e "@echo off \ncoreutils sha1sum %%*" > sha1sum.bat
coreutils echo -e "@echo off \ncoreutils sha224sum %%*" > sha224sum.bat
coreutils echo -e "@echo off \ncoreutils sha256sum %%*" > sha256sum.bat
coreutils echo -e "@echo off \ncoreutils sha3 %%*" > sha3-224sum.bat
coreutils echo -e "@echo off \ncoreutils sha3 %%*" > sha3-256sum.bat
coreutils echo -e "@echo off \ncoreutils sha3 %%*" > sha3-384sum.bat
coreutils echo -e "@echo off \ncoreutils sha3 %%*" > sha3-512sum.bat
coreutils echo -e "@echo off \ncoreutils sha384sum %%*" > sha384sum.bat
coreutils echo -e "@echo off \ncoreutils sha3sum %%*" > sha3sum.bat
coreutils echo -e "@echo off \ncoreutils sha512sum %%*" > sha512sum.bat
coreutils echo -e "@echo off \ncoreutils shake128sum %%*" > shake128sum.bat
coreutils echo -e "@echo off \ncoreutils shake256sum %%*" > shake256sum.bat
coreutils echo -e "@echo off \ncoreutils shred %%*" > shred.bat
coreutils echo -e "@echo off \ncoreutils shuf %%*" > shuf.bat
coreutils echo -e "@echo off \ncoreutils sleep %%*" > sleep.bat
coreutils echo -e "@echo off \ncoreutils sort %%*" > sort.bat
coreutils echo -e "@echo off \ncoreutils split %%*" > split.bat
coreutils echo -e "@echo off \ncoreutils sum %%*" > sum.bat
coreutils echo -e "@echo off \ncoreutils tac %%*" > tac.bat
coreutils echo -e "@echo off \ncoreutils tail %%*" > tail.bat
coreutils echo -e "@echo off \ncoreutils tee %%*" > tee.bat
coreutils echo -e "@echo off \ncoreutils test %%*" > test.bat
coreutils echo -e "@echo off \ncoreutils touch %%*" > touch.bat
coreutils echo -e "@echo off \ncoreutils tr %%*" > tr.bat
coreutils echo -e "@echo off \ncoreutils true %%*" > true.bat
coreutils echo -e "@echo off \ncoreutils truncate %%*" > truncate.bat
coreutils echo -e "@echo off \ncoreutils tsort %%*" > tsort.bat
coreutils echo -e "@echo off \ncoreutils unexpand %%*" > unexpand.bat
coreutils echo -e "@echo off \ncoreutils uniq %%*" > uniq.bat
coreutils echo -e "@echo off \ncoreutils unlink %%*" > unlink.bat
coreutils echo -e "@echo off \ncoreutils vdir %%*" > vdir.bat
coreutils echo -e "@echo off \ncoreutils wc %%*" > wc.bat
coreutils echo -e "@echo off \ncoreutils yes %%*" > yes.bat
